# Generated by Django 3.1.8 on 2021-04-30 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20210428_1730'),
        ('users', '0002_auto_20210427_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_coupons',
            field=models.ManyToManyField(blank=True, related_name='users', to='coupons.Coupon', verbose_name='Избранные купоны'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, help_text='формат: +999999999999', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть введен в формате: "+999999999999". Допускается от 10 до 20 цифр.', regex='^\\+?1?\\d{10,20}$')], verbose_name='номер телефона'),
        ),
    ]
