# Generated by Django 3.1.8 on 2021-05-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_favorite_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnercompany',
            name='web_site',
        ),
        migrations.AddField(
            model_name='partnercompany',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
    ]
