# Generated by Django 3.1.8 on 2021-05-06 06:00

from django.db import migrations, models
import django.db.models.deletion
import django_2gis_maps.fields
import django_2gis_maps.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210505_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompanyMapLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('geolocation', django_2gis_maps.fields.GeoLocationField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='users.partnercompany', verbose_name='Партнер компании')),
            ],
            options={
                'verbose_name': 'Координаты адреса для компании партнера',
                'verbose_name_plural': 'Координаты адреса для компании партнеров',
            },
            bases=(django_2gis_maps.mixins.DoubleGisMixin, models.Model),
        ),
    ]
