# Generated by Django 3.1.8 on 2021-05-06 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_partnercompanymaplocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnercompanymaplocation',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='partnercompanymaplocation',
            name='coordinates',
            field=models.CharField(default=111, help_text='например: 42.876913, 74.600025', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Разрешены символы 0-9,. ', regex='[1234567890,. ]')], verbose_name='Координаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnercompanymaplocation',
            name='phone',
            field=models.CharField(blank=True, help_text='например: +996 000 000 000', max_length=50, verbose_name='Номер телефона'),
        ),
    ]
