# Generated by Django 3.2 on 2021-05-21 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_auto_20210514_0929'),
        ('users', '0008_auto_20210514_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_users', to='coupons.coupon', verbose_name='Купон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный купон пользователя',
                'verbose_name_plural': 'Избранные купоны пользователей',
            },
        ),
    ]
