# Generated by Django 3.2 on 2021-06-23 09:45

import coupons.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userfavoritecoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercompany',
            name='logo',
            field=models.FileField(help_text=('поддерживаемые форматы svg, png, jpg, jpeg. Размер изображения: 200x200',), upload_to=coupons.utils.generate_file_path, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'web', 'webp'])], verbose_name='Логотип'),
        ),
    ]
