# Generated by Django 3.2 on 2021-07-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210625_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='confirmation code'),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmation date'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_registration_finish',
            field=models.BooleanField(default=False, verbose_name='is_registration_finish'),
        ),
    ]
