# Generated by Django 3.1.8 on 2021-04-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20210428_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='bought_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False, verbose_name='Количество купленных'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='activated_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False, verbose_name='Количество активированных купонов'),
        ),
    ]
