# Generated by Django 3.2 on 2021-06-22 05:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_alter_coupon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
