# Generated by Django 3.2 on 2021-06-23 06:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_alter_coupon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='addresses',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='conditions',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Условия'),
        ),
    ]
