# Generated by Django 3.2 on 2021-07-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0010_auto_20210701_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyercoupon',
            name='bought',
            field=models.BooleanField(default=False, verbose_name='Куплено'),
        ),
    ]
