# Generated by Django 3.2 on 2021-07-06 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0011_buyercoupon_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='conditions',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
