# Generated by Django 3.2 on 2021-07-13 08:41

import coupons.utils
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0012_auto_20210706_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_trend',
            field=models.BooleanField(default=False, verbose_name='Добавить в топовые купоны?'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='preview_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='появляет на превью купона, и в слайдере стоит первым', keep_meta=True, quality=0, size=[668, 383], upload_to=coupons.utils.generate_file_path, verbose_name='Превью изображение'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='coupons.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='couponimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[668, 383], upload_to=coupons.utils.generate_file_path, verbose_name='Изображение'),
        ),
    ]
