# Generated by Django 3.2 on 2021-07-15 04:20

import coupons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0013_auto_20210713_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='появляет на превью купона, и в слайдере стоит первым', null=True, upload_to=coupons.utils.generate_file_path, verbose_name='Превью изображение'),
        ),
        migrations.AlterField(
            model_name='couponimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=coupons.utils.generate_file_path, verbose_name='Изображение'),
        ),
    ]
