# Generated by Django 3.2 on 2021-08-05 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0014_auto_20210715_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subcategories', to='coupons.subcategory', verbose_name='Категория в подкатегории')),
            ],
            options={
                'verbose_name': 'Подкатегория в подкатегории',
                'verbose_name_plural': 'Подкатегории в подкатегории',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='sub_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_coupons', to='coupons.subsubcategory', verbose_name='Подкатегория в подкатегории'),
        ),
    ]
