# Generated by Django 3.2 on 2021-08-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0015_auto_20210805_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иконка'),
        ),
    ]
