# Generated by Django 3.2 on 2021-09-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0016_subcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='sub_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_coupons', to='coupons.subsubcategory', verbose_name='Подкатегория в подкатегории'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
