# Generated by Django 3.2 on 2021-10-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0017_auto_20210901_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
