# Generated by Django 3.2 on 2021-12-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0018_coupon_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='position',
        ),
    ]
