version: "3.3"

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python src/manage.py makemigrations &&
             python src/manage.py migrate &&
             python src/manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./backend/izzikg/.env
    depends_on:
      - db
    networks:
      - db-net

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    networks:
      - db-net

  frontend:
    restart: always
    command: > 
      sh -c "npm start"
    container_name: front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    depends_on:
      - django
    networks:
      - db-net

volumes:
  postgres_data:

networks:
  db-net:
    driver: bridge