# Generated by Django 3.1.8 on 2021-05-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageblock',
            options={'ordering': ('position',), 'verbose_name': 'Изображение', 'verbose_name_plural': 'Блок изображений'},
        ),
        migrations.AlterModelOptions(
            name='imageslider',
            options={'ordering': ('position',), 'verbose_name': 'Слайдер изображений', 'verbose_name_plural': 'Слайдер изображений на главной странице'},
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
    ]
