# Generated by Django 3.1.8 on 2021-05-06 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210505_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMapLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(help_text='например: 42.876913, 74.600025', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Разрешены символы 0-9,. ', regex='[1234567890,. ]')], verbose_name='Координаты')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Координаты на карте',
                'verbose_name_plural': 'Координаты на карте',
            },
        ),
    ]
