# Generated by Django 3.1.8 on 2021-05-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_ourmaplocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='app_store',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='play_market',
        ),
    ]
