# Generated by Django 3.2 on 2021-06-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_footerfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToMakeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Как сделать заказ',
                'verbose_name_plural': 'Как сделать заказ',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способ оплаты',
            },
        ),
    ]
