// User
export const USER_AUTH_REQUEST = "USER_AUTH_REQUEST"
export const USER_LOGOUT = "USER_LOGOUT"
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS"
export const USER_AUTH_FAILURE = "USER_AUTH_FAILURE"

// Tags
export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST'
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS'
export const GET_TAGS_FAILURE = 'GET_TAGS_SUCCESS'

//Info

export const GET_PAYMENT_WAYS = 'GET_PAYMENT_WAYS'
export const GET_MAKE_ORDER = 'GET_MAKE_ORDER'
export const GET_ANSWER_QUESTION = 'GET_ANSWER_QUESTION'
export const GET_HELP_ANSWERS = 'GET_HELP_ANSWERS'
export const GET_NETWORKS = 'GET_NETWORKS'
export const GET_ABOUT_US = 'GET_ABOUT_US'
export const GET_PRIVACY_POLICY = "GET_PRIVACY_POLICY"
export const GET_PUBLIC_OFFER = "GET_PUBLIC_OFFER"
export const GET_REQUISITES = "GET_REQUISITES"

//Slider

export const GET_BANNER_SLIDER = 'GET_BANNER_SLIDER'
export const GET_BANNER_CAROUSEL = 'GET_BANNER_CAROUSEL'

// Categories
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST"
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE"

export const GET_NEW_CATEGORIES = "GET_NEW_CATEGORIES"
export const SET_LOADED = "SET_LOADED"

// Coupons

export const SET_COUPONS = 'SET_COUPONS'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const GET_DETAILS_COUPONS = 'GET_DETAILS_COUPONS'
export const GET_SEARCH_COUPON = 'GET_SEARCH_COUPON'
export const ADD_COUPON_TO_FAVORITE = 'ADD_COUPON_TO_FAVORITE'
export const REMOVE_COUPON_TO_FAVORITE = 'REMOVE_COUPON_TO_FAVORITE'
export const SET_MY_COUPONS = 'SET_MY_COUPONS'
export const SET_MY_STOCKS = 'SET_MY_STOCKS'
export const GET_MY_COUPONS_ACTIVE = "GET_MY_COUPONS_ACTIVE"

export const GET_COUPONS_CATEGORY_REQUEST = "GET_COUPONS_CATEGORY_REQUEST"
export const GET_COUPONS_CATEGORY_SUCCESS = "GET_COUPONS_CATEGORY_SUCCESS"
export const GET_COUPONS_CATEGORY_FAILURE = "GET_COUPONS_CATEGORY_FAILURE"
export const COUPONS_PAGINATION = 'COUPONS_PAGINATION'

//About

export const GET_ABOUT_MAP = "GET_ABOUT_MAP"
